Teardown Project Review Request
JelilFaisalAbudu/teardown pull request #2
Opened 2020-03-23 10:23 UTC by JelilFaisalAbudu

# Teardown Project Review Request

- All the features were implemented;
- Did a grayscale and not a clone of the project to study UX;
- HTML Validator checked 
-CSS linter checked.
- Awaiting for code review from TSE:

2020-03-23 10:41 UTC, uryelah requested changes
Hello **Faisal Abudu** & **Felipe Dacal Fragoso**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all, good job with this project.🎇**
You guys did a great job paying attention to the page elements and adding even the transformations.

There are still some minor issues to work through so hang in there 💪 

---------    

### Required changes 🛠 
---------
**Check the required changes in the comments below** 🔽

2020-03-23 10:41 UTC, uryelah commented on index.html
> +    <header class="header">
- [ ] Use the `<nav>` tag for the nav bar. It's more semantic.

2020-03-23 10:41 UTC, uryelah commented on index.html
> +        <div class="top-box">
- [ ] `<div>`s of the .top-box class and other divs that represent articles should use the `<article>` tag. Make sure you check all the `div`s that have self-contained element representing an article and use the semantic tag for them.

2020-03-23 10:41 UTC, uryelah commented on index.html
> +    <footer class="footer">
- [ ] The footer should contain centered **links**. Remember to add the `<a>` tags.

2020-03-23 10:41 UTC, uryelah commented
**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-03-23 11:05 UTC, uryelah commented
Great job with the required changes.
Your project is good enough to pass.

### Your project is approved! 🎊 🥅 💛 
### 
**You may close this Pull Request and merge the changes**

-------

## Optional Improvements

- [ ] [OPTIONAL] For the `<article>` tags that contain multiple articles within themselves change the tag to `<section>` for a more semantic HTML. [ Check this MDN article with examples of a good semantic HTML structure.](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines)
-------

**Keep being an awesome dev, good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

2020-03-23 12:11 UTC, merged

2020-03-26 07:32 UTC, fdfragoso commented on index.html
> +        </artic>
article and not artic